#ifndef __APPLICATIONCURRENTDIRECTORYMANAGERNBUILDMACRO_HPP__
#define __APPLICATIONCURRENTDIRECTORYMANAGERBUILDMACRO_HPP__
#ifdef APPLICATIONCURRENTDIRECTORYMANAGER_EXPORTS
#define APPDIR __declspec(dllexport)
#else
#define APPDIR __declspec(dllimport)
#endif
#endif
